### ISSUE TITLE
Allow multiple inactive devices at reference bus 

### ISSUE THREAD

**Issue by m-bossart** [NREL-SIIP/PowerSimulationsDynamics.jl#105]
Currently, only one source or generator is allowed at the reference bus so that there is a single frequency reference:
https://github.com/NREL-SIIP/PowerSimulationsDynamics.jl/blob/9f3ebf8fa9eb087ad456f95afc611bf9cf385156/src/base/frequency_reference.jl#L38-L43

Is it possible to change (loosen) this requirement so that multiple sources/generators can be present at the reference bus as long as only one of the devices is active? The frequency reference could be attached to the device that is active.

**Comment by rodrigomha** [comment]
@jd-lara How do you think we should manage this? I don't think we have availability implemented yet, but I'm thinking we can allow multiple devices connected as long as we specify which device provides the reference frequency

**Comment by jd-lara** [comment]
We can classify this as a bug where we need to consider the availability status of the generators when making this calculation. I added this already in the upcoming branch for v0.7 but we should make a patch in master to address this issue.

**Comment by jd-lara** [comment]
we want to do: 

```julia
 x ->
            PSY.get_bustype(PSY.get_bus(x)) == PSY.BusTypes.REF &&
                !isa(x, PSY.ElectricLoad) && PSY.get_available(x),
    )
```
