### ISSUE TITLE
Allow multiple injectors at reference bus

### ISSUE THREAD

**Issue by rodrigomha** [NREL-SIIP/PowerSimulationsDynamics.jl#18]
Currently, only device is allowed at the reference bus, that is used to provide the frequency reference of the system. 

To allow multiple injectors, the logic should follows:
- If at least one Source is connected at the reference bus, then `omega_sys = 1.0`.
- If only one Dynamic Injector (and no Source) is connected at reference bus, then `omega_sys = omega_device`.
- If multiple Dynamic Injectors (and no Source) are connected at reference bus, use a strategy to define which device will be the reference frequency `omega_sys = omega_selected_device`.

**Comment by jd-lara** [comment]
This is only a problem for the case where the frequency is calculated on a reference bus. This could be resolved with other frequency estimate method. x-ref: #60
