### ISSUE TITLE
read_results is not defined 

### ISSUE THREAD

**Issue by mkaracelebi** [NREL-SIIP/PowerSimulationsDynamics.jl#181]
read_results( ) function is not defined in the latest version.

**Comment by jd-lara** [comment]
This issue makes me think again that you are using the incorrect version of PowerSimulationsDynamics. The function `read_results` was introduced in v0.8.5.

**Comment by mkaracelebi** [comment]
Thanks Jose, indeed my version was off but it is quite strange since I have imported all packages this week. Why did Julia import an older version instead of the newest?

**Comment by jd-lara** [comment]
sometimes the package manager will resolve to older versions if the dependency constraints allow it.

**Comment by kalpaniosu** [comment]
Can someone provide the read_results function code. I cannot find it in my version

**Comment by rodrigomha** [comment]
> Can someone provide the read_results function code. I cannot find it in my version

It simply returns the SimulationResults struct. See here: https://github.com/NREL-Sienna/PowerSimulationsDynamics.jl/blob/012e68c55b61f8aca6493c7fc7ae422ebd48bc90/src/base/simulation.jl#L555

The SimulationResults struct is defined here:
https://github.com/NREL-Sienna/PowerSimulationsDynamics.jl/blob/012e68c55b61f8aca6493c7fc7ae422ebd48bc90/src/base/simulation_results.jl

**Comment by kalpaniosu** [comment]
> > Can someone provide the read_results function code. I cannot find it in my version
> 
> It simply returns the SimulationResults struct. See here:
> 
> https://github.com/NREL-Sienna/PowerSimulationsDynamics.jl/blob/012e68c55b61f8aca6493c7fc7ae422ebd48bc90/src/base/simulation.jl#L555
> 
> The SimulationResults struct is defined here: https://github.com/NREL-Sienna/PowerSimulationsDynamics.jl/blob/012e68c55b61f8aca6493c7fc7ae422ebd48bc90/src/base/simulation_results.jl

Thank you so much for your reply.Appreciate it.
