### ISSUE TITLE
Update on documents BranchTrip( )

### ISSUE THREAD

**Issue by mkaracelebi** [NREL-SIIP/PowerSimulationsDynamics.jl#182]
In the documents BranchTrip( ) has 3 different inputs (time, type, name) but in the latest version it produces a MethodError and source code indicates 2 inputs only (time, name).

**Comment by jd-lara** [comment]
@mkaracelebi can you confirm which version are you using? The current syntax for a branch trip is as in the documentation ```BranchTrip(1.0, Line, "BUS 1-BUS 2-i_1"), ``` 

if you do 

```
julia> ] st 
```

and paste the info it will be easier to help you.

**Comment by mkaracelebi** [comment]
Version problem.
