### ISSUE TITLE
Document update - ResidualModel & ImplicitModel

### ISSUE THREAD

**Issue by mkaracelebi** [NREL-SIIP/PowerSimulationsDynamics.jl#183]
Documents show the usage of ResidualModel in the simulation but it is not defined in the latest version of the package. I think it is replaced by ImplicitModel.

**Comment by jd-lara** [comment]
@mkaracelebi it looks like you might be reading old documentation. Version 0.8.5 shows the following 

<img width="797" alt="image" src="https://user-images.githubusercontent.com/16385323/152010638-368bfdf9-8e8f-43ee-be21-ebed021d0898.png">
