### ISSUE TITLE
Create specific helper functions to retrieve information or avoid users to create extra structs.

### ISSUE THREAD

**Issue by rodrigomha** [NREL-SIIP/PowerSimulationsDynamics.jl#2]
Proposed ideas to do:

- [x] Create a helper function to retrieve a dictionary with control references: P_ref, Q_ref, V_ref, omega_ref.
- [x] Create functions for no_structs. For example create no_avr() that simply creates an AVRFixed(1.0), or no_pss() that creates PSSFixed(0.0). This will avoid users to define extra structs when those are not required.

**Comment by jd-lara** [comment]
Include this in the display of simulation along with initial conditions and other info.

**Comment by rodrigomha** [comment]
Closed via #135
