### ISSUE TITLE
Implement Grid Following Inverter Model

### ISSUE THREAD

**Issue by rodrigomha** [NREL-SIIP/PowerSimulationsDynamics.jl#67]
The model should include a way to skip the InnerControl model. This will be the implementation used:
https://www.nrel.gov/docs/fy17osti/68202.pdf and https://www.nrel.gov/docs/fy21osti/78402.pdf

To do:
- [x] OuterControl
- [x] InnerControl
- [x] ReducedOrderPLL

**Comment by jd-lara** [comment]
The PR in PSY for the new structs in merged in master of PSY and just needs https://github.com/NREL-SIIP/PowerSystems.jl/pull/761 to be merged for a new release.

**Comment by jd-lara** [comment]
@rodrigomha add requirement that PSY > 1.7 version for this to work

**Comment by jd-lara** [comment]
closed via #82
