### ISSUE TITLE
Docs link broken 

### ISSUE THREAD

**Issue by cuihantao** [NREL-SIIP/PowerSimulationsDynamics.jl#8]
The link to the docs by clinking on the documentation badge is not working.

**Comment by rodrigomha** [comment]
You are right. Docs are not being deployed correctly. For now, check the dev version on:

https://nrel-siip.github.io/PowerSimulationsDynamics.jl/dev/

**Comment by cuihantao** [comment]
Got it. Thanks.

**Comment by jd-lara** [comment]
The docs will be deployed correctly after the auto release form GitHub.
